### ISSUE TITLE
user passwords ?

### ISSUE THREAD

**Issue by jmls** [hpi-schul-cloud/ldap-test-tools#5]
I may be missing something here - but what is the password for the generated users in the system ?

**Comment by jmls** [comment]
I cannot find the field in the ldap admin window either ;)

**Comment by mamutmk5** [comment]
The passwords are not important and necessary. This tool is used to  generate an request set of users, schools and classes as Test data for LDAP Sync test.

**Any additional question?**

**Comment by mamutmk5** [comment]
@jmls if you have any questions so far for this topic feel free to ask, if not i will close this issue at 01.10.2021
